sudo: false
language: java
jdk:
    - oraclejdk8
install: ./gradlew assemble
script: ./gradlew check
cache:
    directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/gradle-2.4-all/
